# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('gateway_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, default='', max_length=128)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('distinct_to', models.BooleanField(default=False)),
                ('auth_username', models.CharField(blank=True, default='', max_length=128)),
                ('realm', models.CharField(blank=True, default='', max_length=256)),
                ('from_user', models.CharField(blank=True, default='', max_length=128)),
                ('from_domain', models.CharField(blank=True, default='', max_length=256)),
                ('proxy', models.CharField(blank=True, default='', max_length=256)),
                ('register_proxy', models.CharField(blank=True, default='', max_length=256)),
                ('outbound_proxy', models.CharField(blank=True, default='', max_length=256)),
                ('expire_seconds', models.IntegerField(default=3600)),
                ('register', models.BooleanField(default=True)),
                ('register_transport', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS')], default='udp', max_length=8)),
                ('retry_seconds', models.IntegerField(default=30)),
                ('extension', models.CharField(default='auto_to_user', max_length=32)),
                ('ping', models.CharField(blank=True, default='', max_length=64)),
                ('ping_max', models.IntegerField(default=3)),
                ('ping_min', models.IntegerField(default=1)),
                ('caller_id_in_from', models.BooleanField(default=False)),
                ('codec_prefs', models.CharField(default='PCMU,PCMA', max_length=128)),
                ('inbound_codec_prefs', models.CharField(default='PCMU,PCMA', max_length=128)),
                ('outbound_codec_prefs', models.CharField(default='PCMU,PCMA', max_length=128)),
                ('profile', models.CharField(default='external', max_length=64)),
                ('gateway_enabled', models.BooleanField(default=True)),
                ('gateway_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='core.domain')),
            ],
            options={
                'db_table': 'v_gateways',
                'unique_together': {('domain', 'gateway')},
            },
        ),
    ]
