# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0003_add_trunk_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gateway',
            unique_together=set(),
        ),
    ]
