# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCondition',
            fields=[
                ('dialplan_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dialplan_name', models.CharField(max_length=255)),
                ('dialplan_extension', models.CharField(blank=True, max_length=255)),
                ('dialplan_context', models.CharField(blank=True, max_length=128)),
                ('dialplan_enabled', models.BooleanField(default=True)),
                ('dialplan_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_time_conditions',
            },
        ),
        migrations.CreateModel(
            name='TimeConditionRange',
            fields=[
                ('time_condition_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_condition_order', models.IntegerField(default=900)),
                ('time_condition_enabled', models.BooleanField(default=True)),
                ('time_condition_year', models.CharField(blank=True, max_length=64)),
                ('time_condition_yday', models.CharField(blank=True, max_length=64)),
                ('time_condition_mon', models.CharField(blank=True, max_length=64)),
                ('time_condition_mday', models.CharField(blank=True, max_length=64)),
                ('time_condition_week', models.CharField(blank=True, max_length=64)),
                ('time_condition_mweek', models.CharField(blank=True, max_length=64)),
                ('time_condition_wday', models.CharField(blank=True, max_length=64)),
                ('time_condition_hour', models.CharField(blank=True, max_length=64)),
                ('time_condition_minute', models.CharField(blank=True, max_length=64)),
                ('time_condition_minute_of_day', models.CharField(blank=True, max_length=64)),
                ('time_condition_time_of_day', models.CharField(blank=True, max_length=64)),
                ('time_condition_date_time', models.CharField(blank=True, max_length=64)),
                ('time_condition_destination_number', models.CharField(blank=True, max_length=255)),
                ('time_condition_destination_action', models.CharField(blank=True, max_length=64)),
                ('time_condition_destination_app', models.CharField(blank=True, max_length=128)),
                ('time_condition_destination_param', models.CharField(blank=True, max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('dialplan', models.ForeignKey(db_column='dialplan_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='time_conditions.timecondition')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_time_condition_ranges',
                'ordering': ['time_condition_order'],
            },
        ),
    ]
