# Generated by Django 5.1.5 on 2026-02-19 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionTemplate',
            fields=[
                ('template_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=32)),
                ('template_name', models.CharField(max_length=128)),
                ('template_content', models.TextField()),
                ('content_type', models.CharField(default='text/xml', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'v_provision_templates',
                'unique_together': {('vendor', 'model', 'firmware_version', 'template_name')},
            },
        ),
    ]
