# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('queue_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_name', models.CharField(max_length=128)),
                ('queue_extension', models.CharField(blank=True, default='', max_length=32)),
                ('queue_greet_long', models.CharField(blank=True, default='', max_length=256)),
                ('queue_greet_short', models.CharField(blank=True, default='', max_length=256)),
                ('queue_moh_sound', models.CharField(blank=True, default='', max_length=256)),
                ('queue_time_base_score', models.CharField(default='queue', max_length=16)),
                ('queue_max_wait_time', models.IntegerField(default=0)),
                ('queue_max_wait_time_with_no_agent', models.IntegerField(default=0)),
                ('queue_timeout_action', models.CharField(blank=True, default='', max_length=256)),
                ('queue_discard_abandoned_after', models.IntegerField(default=900)),
                ('queue_abandoned_resume_allowed', models.BooleanField(default=False)),
                ('strategy', models.CharField(choices=[('ring-all', 'Ring All'), ('longest-idle-agent', 'Longest Idle Agent'), ('round-robin', 'Round Robin'), ('top-down', 'Top Down'), ('agent-with-least-talk-time', 'Least Talk Time'), ('agent-with-fewest-calls', 'Fewest Calls'), ('sequentially-by-agent-order', 'Sequential'), ('random', 'Random')], default='round-robin', max_length=64)),
                ('queue_tier_rules_apply', models.BooleanField(default=False)),
                ('queue_tier_rule_wait_second', models.IntegerField(default=300)),
                ('queue_tier_rule_no_agent_no_wait', models.BooleanField(default=False)),
                ('queue_tier_rule_wait_multiply_level', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='call_centers', to='core.domain')),
            ],
            options={
                'db_table': 'v_call_center_queues',
                'unique_together': {('domain', 'queue_name')},
            },
        ),
        migrations.CreateModel(
            name='CallCenterAgent',
            fields=[
                ('agent_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=128)),
                ('agent_type', models.CharField(choices=[('callback', 'Callback'), ('uuid-standby', 'UUID Standby')], default='callback', max_length=32)),
                ('agent_contact', models.CharField(blank=True, default='', max_length=256)),
                ('agent_status', models.CharField(default='Available', max_length=32)),
                ('agent_state', models.CharField(default='Waiting', max_length=32)),
                ('max_no_answer', models.IntegerField(default=3)),
                ('wrap_up_time', models.IntegerField(default=10)),
                ('reject_delay_time', models.IntegerField(default=10)),
                ('busy_delay_time', models.IntegerField(default=10)),
                ('no_answer_delay_time', models.IntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='call_center_agents', to='core.domain')),
            ],
            options={
                'db_table': 'v_call_center_agents',
                'unique_together': {('domain', 'agent_name')},
            },
        ),
        migrations.CreateModel(
            name='CallCenterTier',
            fields=[
                ('tier_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_agent', models.CharField(blank=True, default='', max_length=128)),
                ('tier_level', models.IntegerField(default=1)),
                ('tier_position', models.IntegerField(default=1)),
                ('agent', models.ForeignKey(db_column='agent_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='call_centers.callcenteragent')),
                ('call_center', models.ForeignKey(db_column='queue_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='call_centers.callcenter')),
                ('domain', models.ForeignKey(db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_call_center_tiers',
                'unique_together': {('call_center', 'agent')},
            },
        ),
    ]
