# Generated by Django 5.1.5 on 2026-02-19 08:05

import django.db.models.deletion
from django.db import migrations, models


def backfill_tenant_from_domain(apps, schema_editor):
    """Back-fill tenant from domain.tenant for all models in this migration."""
    app_label = 'call_centers'
    model_names = ['Callcenter', 'Callcenteragent', 'Callcentertier']
    for model_name in model_names:
        try:
            Model = apps.get_model(app_label, model_name)
            objs = list(Model.objects.select_related('domain').filter(domain__isnull=False, tenant__isnull=True))
            for obj in objs:
                if obj.domain and getattr(obj.domain, 'tenant_id', None):
                    obj.tenant_id = obj.domain.tenant_id
                    obj.save(update_fields=['tenant_id'])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('call_centers', '0001_initial'),
        ('core', '0003_fix_fk_related_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callcenter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='callcenteragent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='callcenter',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='callcenteragent',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='callcentertier',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='callcenter',
            unique_together={('tenant', 'queue_name')},
        ),
        migrations.AlterUniqueTogether(
            name='callcenteragent',
            unique_together={('tenant', 'agent_name')},
        ),
        migrations.RunPython(
            backfill_tenant_from_domain,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
