# Generated by Django 5.1.5 on 2026-02-19 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_label', models.CharField(max_length=255)),
                ('module_name', models.CharField(max_length=255, unique=True)),
                ('module_category', models.CharField(blank=True, max_length=128)),
                ('module_sequence', models.IntegerField(default=100)),
                ('module_enabled', models.BooleanField(default=True)),
                ('module_default_enabled', models.CharField(default='true', max_length=10)),
                ('module_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'v_modules',
                'ordering': ['module_category', 'module_sequence'],
            },
        ),
    ]
