# Generated by Django 5.1.5 on 2026-03-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_default_gateway_and_more'),
        ('outbound_routes', '0002_caller_id_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='outboundroute',
            name='unique_outbound_route_per_tenant',
        ),
        migrations.AlterField(
            model_name='outboundroute',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
