# Generated by Django 5.2.11 on 2026-03-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbound_routes', '0003_remove_outboundroute_unique_outbound_route_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outboundroute',
            unique_together=set(),
        ),
    ]
