# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SipProfile',
            fields=[
                ('sip_profile_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sip_profile_name', models.CharField(max_length=64, unique=True)),
                ('sip_profile_hostname', models.CharField(blank=True, default='', max_length=256)),
                ('sip_profile_enabled', models.BooleanField(default=True)),
                ('sip_profile_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_sip_profiles',
            },
        ),
        migrations.CreateModel(
            name='SipProfileDomain',
            fields=[
                ('sip_profile_domain_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sip_profile_domain_name', models.CharField(max_length=128)),
                ('sip_profile_domain_alias', models.BooleanField(default=False)),
                ('sip_profile_domain_parse', models.BooleanField(default=False)),
                ('sip_profile', models.ForeignKey(db_column='sip_profile_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='sip_profiles.sipprofile')),
            ],
            options={
                'db_table': 'v_sip_profile_domains',
            },
        ),
        migrations.CreateModel(
            name='SipProfileSetting',
            fields=[
                ('sip_profile_setting_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sip_profile_setting_name', models.CharField(max_length=128)),
                ('sip_profile_setting_value', models.TextField(blank=True, default='')),
                ('sip_profile_setting_enabled', models.BooleanField(default=True)),
                ('sip_profile_setting_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sip_profile', models.ForeignKey(db_column='sip_profile_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sip_profiles.sipprofile')),
            ],
            options={
                'db_table': 'v_sip_profile_settings',
            },
        ),
    ]
