# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicOnHold',
            fields=[
                ('music_on_hold_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('music_on_hold_name', models.CharField(max_length=255)),
                ('music_on_hold_path', models.CharField(blank=True, max_length=512)),
                ('music_on_hold_rate', models.CharField(default='8000', max_length=10)),
                ('music_on_hold_shuffle', models.BooleanField(default=False)),
                ('music_on_hold_channels', models.IntegerField(default=1)),
                ('music_on_hold_interval', models.IntegerField(default=20)),
                ('music_on_hold_timer_name', models.CharField(blank=True, max_length=64)),
                ('music_on_hold_chime_list', models.TextField(blank=True)),
                ('music_on_hold_chime_freq', models.IntegerField(default=0)),
                ('music_on_hold_chime_max', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_music_on_hold',
            },
        ),
    ]
