"""Celery tasks for the access_controls app."""
import logging

from celery import shared_task

logger = logging.getLogger(__name__)


@shared_task(bind=True, max_retries=3, default_retry_delay=10)
def reload_access_control(self, access_control_uuid: str):
    """Trigger a FreeSWITCH XML reload after an access control change.

    Delegates to ``esl.tasks.reload_xml`` which issues ``reloadxml`` over ESL.
    Retries up to 3 times with a 10-second backoff on ESL connection failures.
    """
    try:
        from esl.tasks import reload_xml  # noqa: PLC0415 – late import required
        reload_xml.delay()
        logger.info(
            'reload_access_control: triggered reloadxml for access_control %s',
            access_control_uuid,
        )
    except Exception as exc:
        logger.warning(
            'reload_access_control: ESL task failed for %s: %s – retrying',
            access_control_uuid,
            exc,
        )
        raise self.retry(exc=exc)


@shared_task(bind=True, max_retries=3, default_retry_delay=10)
def reload_all_access_controls(self):
    """Reload all access control lists in FreeSWITCH.

    Issues ``reloadxml`` which causes FreeSWITCH to re-read the acl.conf.xml
    generated by the XML cURL handler.
    """
    try:
        from esl.tasks import reload_xml  # noqa: PLC0415
        reload_xml.delay()
        logger.info('reload_all_access_controls: triggered reloadxml for all ACLs')
    except Exception as exc:
        logger.warning(
            'reload_all_access_controls: ESL task failed: %s – retrying',
            exc,
        )
        raise self.retry(exc=exc)
