# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicemailGreeting',
            fields=[
                ('voicemail_greeting_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voicemail_id', models.CharField(max_length=255)),
                ('greeting_id', models.IntegerField(default=0)),
                ('greeting_name', models.CharField(blank=True, max_length=255)),
                ('greeting_filename', models.CharField(max_length=512)),
                ('greeting_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_voicemail_greetings',
            },
        ),
    ]
