# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberTranslation',
            fields=[
                ('number_translation_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_translation_name', models.CharField(max_length=255)),
                ('number_translation_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_number_translations',
            },
        ),
        migrations.CreateModel(
            name='NumberTranslationDetail',
            fields=[
                ('number_translation_detail_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_translation_detail_order', models.IntegerField(default=10)),
                ('number_translation_detail_condition_field', models.CharField(blank=True, max_length=64)),
                ('number_translation_detail_condition_expression', models.CharField(blank=True, max_length=255)),
                ('number_translation_detail_action_expression', models.CharField(blank=True, max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('number_translation', models.ForeignKey(db_column='number_translation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='number_translations.numbertranslation')),
            ],
            options={
                'db_table': 'v_number_translation_details',
                'ordering': ['number_translation_detail_order'],
            },
        ),
    ]
