# Generated by Django 6.0.3 on 2026-06-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_parking', '0001_initial'),
        ('core', '0014_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='callparkingslot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callparkingslot',
            name='parked_call_uuid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='callparkingslot',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
