# Generated by Django 6.0.3 on 2026-04-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_parking', '0001_initial'),
        ('core', '0012_add_is_occupied_parked_call_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callparkingslot',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
