# Generated by Django 6.0.3 on 2026-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_parking', '0002_add_is_occupied_parked_call_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='callparkingslot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callparkingslot',
            name='parked_call_uuid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
