# Generated by Django 6.0.3 on 2026-06-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_parking', '0002_callparkingslot_is_occupied_and_more'),
        ('call_parking', '0003_add_is_occupied_parked_call_uuid'),
    ]

    operations = [
    ]
