# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowMe',
            fields=[
                ('follow_me_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_me_name', models.CharField(max_length=255)),
                ('follow_me_context', models.CharField(blank=True, max_length=128)),
                ('follow_me_prompt', models.BooleanField(default=False)),
                ('follow_me_cid_name_prefix', models.CharField(blank=True, max_length=64)),
                ('follow_me_missed_call_email', models.CharField(blank=True, max_length=255)),
                ('follow_me_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_follow_me',
            },
        ),
        migrations.CreateModel(
            name='FollowMeDestination',
            fields=[
                ('follow_me_destination_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_me_destination_order', models.IntegerField(default=1)),
                ('follow_me_destination', models.CharField(max_length=255)),
                ('follow_me_delay', models.IntegerField(default=0)),
                ('follow_me_timeout', models.IntegerField(default=30)),
                ('follow_me_prompt', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('follow_me', models.ForeignKey(db_column='follow_me_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='follow_me.followme')),
            ],
            options={
                'db_table': 'v_follow_me_destinations',
                'ordering': ['follow_me_destination_order'],
            },
        ),
    ]
