# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fifo',
            fields=[
                ('fifo_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fifo_name', models.CharField(max_length=255)),
                ('fifo_label', models.CharField(blank=True, max_length=255)),
                ('fifo_extension', models.CharField(blank=True, max_length=255)),
                ('fifo_announcement', models.CharField(blank=True, max_length=255)),
                ('fifo_music', models.CharField(blank=True, max_length=255)),
                ('fifo_strategy', models.CharField(default='default', max_length=64)),
                ('fifo_caller_hang_up_opt', models.CharField(blank=True, max_length=10)),
                ('fifo_caller_exit_key', models.CharField(blank=True, max_length=10)),
                ('fifo_max_wait_time', models.IntegerField(default=0)),
                ('fifo_max_wait_time_with_no_agent', models.IntegerField(default=0)),
                ('fifo_timeout_priority', models.CharField(blank=True, max_length=10)),
                ('fifo_pop_on_lost_agent', models.CharField(default='true', max_length=10)),
                ('fifo_enabled', models.BooleanField(default=True)),
                ('fifo_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_fifo',
            },
        ),
        migrations.CreateModel(
            name='FifoCallers',
            fields=[
                ('fifo_caller_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fifo_caller_caller_id_name', models.CharField(blank=True, max_length=255)),
                ('fifo_caller_caller_id_number', models.CharField(blank=True, max_length=255)),
                ('fifo_caller_status', models.CharField(default='waiting', max_length=20)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('fifo', models.ForeignKey(db_column='fifo_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='callers', to='fifo.fifo')),
            ],
            options={
                'db_table': 'v_fifo_callers',
            },
        ),
    ]
