# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlCdr',
            fields=[
                ('xml_cdr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_id_name', models.CharField(blank=True, default='', max_length=128)),
                ('caller_id_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('caller_destination', models.CharField(blank=True, default='', max_length=32)),
                ('destination_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('context', models.CharField(blank=True, default='', max_length=128)),
                ('start_epoch', models.BigIntegerField(default=0)),
                ('start_stamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('answer_epoch', models.BigIntegerField(default=0)),
                ('answer_stamp', models.DateTimeField(blank=True, null=True)),
                ('end_epoch', models.BigIntegerField(default=0)),
                ('end_stamp', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(db_index=True, default=0)),
                ('mduration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(db_index=True, default=0)),
                ('billmsec', models.IntegerField(default=0)),
                ('bridge_uuid', models.UUIDField(blank=True, null=True)),
                ('read_codec', models.CharField(blank=True, default='', max_length=32)),
                ('read_rate', models.CharField(blank=True, default='', max_length=8)),
                ('write_codec', models.CharField(blank=True, default='', max_length=32)),
                ('write_rate', models.CharField(blank=True, default='', max_length=8)),
                ('remote_media_ip', models.CharField(blank=True, default='', max_length=64)),
                ('network_addr', models.CharField(blank=True, default='', max_length=64)),
                ('record_path', models.CharField(blank=True, default='', max_length=512)),
                ('record_name', models.CharField(blank=True, default='', max_length=256)),
                ('leg', models.CharField(choices=[('a', 'A-leg'), ('b', 'B-leg')], default='a', max_length=8)),
                ('pdd_ms', models.IntegerField(default=0)),
                ('last_app', models.CharField(blank=True, default='', max_length=64)),
                ('last_arg', models.CharField(blank=True, default='', max_length=256)),
                ('cc_queue', models.CharField(blank=True, default='', max_length=256)),
                ('cc_agent', models.CharField(blank=True, default='', max_length=256)),
                ('waitsec', models.IntegerField(default=0)),
                ('conference_name', models.CharField(blank=True, default='', max_length=256)),
                ('hangup_cause', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('hangup_cause_q850', models.IntegerField(default=0)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('local', 'Local')], default='inbound', max_length=16)),
                ('missed_call', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdr_records', to='core.domain')),
            ],
            options={
                'db_table': 'v_xml_cdr',
                'ordering': ['-start_stamp'],
                'indexes': [models.Index(fields=['start_stamp'], name='v_xml_cdr_start_s_e15627_idx'), models.Index(fields=['caller_id_number'], name='v_xml_cdr_caller__d9a1a2_idx'), models.Index(fields=['destination_number'], name='v_xml_cdr_destina_cb78f3_idx'), models.Index(fields=['hangup_cause'], name='v_xml_cdr_hangup__d8a8a7_idx')],
            },
        ),
    ]
