# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_cdr', '0004_add_bypass_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlcdr',
            name='call_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmlcdr',
            name='bridge_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
