# Generated by Django 5.1.5 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_default_gateway_and_more'),
        ('xml_cdr', '0006_merge'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='xmlcdr',
            index=models.Index(fields=['tenant', 'start_stamp'], name='v_xml_cdr_tenant__23fa5f_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlcdr',
            index=models.Index(fields=['tenant', 'caller_id_number'], name='v_xml_cdr_tenant__e60794_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlcdr',
            index=models.Index(fields=['direction', 'start_stamp'], name='v_xml_cdr_directi_105a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlcdr',
            index=models.Index(fields=['missed_call', 'start_stamp'], name='v_xml_cdr_missed__34e856_idx'),
        ),
    ]
