<<<<<<< Updated upstream
# Generated by Django 6.0.3 on 2026-06-02 10:37
=======
# Generated by Django 6.0.3 on 2026-04-28 01:59
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_cdr', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlcdr',
            name='last_arg',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
