# Generated by Django 6.0.3 on 2026-06-17 04:32

from django.db import migrations, models


def backfill_denormalized(apps, schema_editor):
    """Copy tenant/domain identity from the FK columns into the new denormalized
    columns. Done in raw set-based SQL (1.39M rows) — a Python loop would be far
    too slow. The FK db_columns are tenant_uuid / domain_uuid; we read tenant_code
    and domain_name from the joined core tables."""
    db = schema_editor.connection.alias
    # This backfill joins v_tenants/v_domains, which only exist in the main DB.
    # When building the schema in the separate 'cdr' DB the table starts empty and
    # data is copied in afterwards, so there is nothing to backfill there — skip.
    if db != 'default':
        return
    with schema_editor.connection.cursor() as cur:
        cur.execute("""
            UPDATE v_xml_cdr AS c
               SET tenant_uuid_denorm = c.tenant_uuid,
                   tenant_code        = COALESCE(t.tenant_code, ''),
                   domain_uuid_denorm = c.domain_uuid,
                   domain_name        = COALESCE(d.domain_name, '')
              FROM v_xml_cdr c2
              LEFT JOIN v_tenants t ON t.tenant_uuid = c2.tenant_uuid
              LEFT JOIN v_domains d ON d.domain_uuid = c2.domain_uuid
             WHERE c.xml_cdr_uuid = c2.xml_cdr_uuid
               AND (c.tenant_uuid IS NOT NULL OR c.domain_uuid IS NOT NULL)
        """)


def noop_reverse(apps, schema_editor):
    # Reverse just clears the denormalized columns; the FKs are untouched, so the
    # migration is fully reversible.
    with schema_editor.connection.cursor() as cur:
        cur.execute("""
            UPDATE v_xml_cdr
               SET tenant_uuid_denorm = NULL, tenant_code = '',
                   domain_uuid_denorm = NULL, domain_name = ''
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('xml_cdr', '0011_xmlcdr_sip_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlcdr',
            name='domain_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='xmlcdr',
            name='domain_uuid_val',
            field=models.UUIDField(blank=True, db_column='domain_uuid_denorm', null=True),
        ),
        migrations.AddField(
            model_name='xmlcdr',
            name='tenant_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='xmlcdr',
            name='tenant_uuid_val',
            field=models.UUIDField(blank=True, db_column='tenant_uuid_denorm', db_index=True, null=True),
        ),
        migrations.RunPython(backfill_denormalized, noop_reverse),
    ]
