# Generated by Django 6.0.3 on 2026-06-17 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_allowed_fax_uuids'),
        ('xml_cdr', '0012_denormalize_tenant_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlcdr',
            name='domain',
            field=models.ForeignKey(blank=True, db_column='domain_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cdr_records', to='core.domain'),
        ),
        migrations.AlterField(
            model_name='xmlcdr',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
