# Generated by Django 6.0.3 on 2026-06-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_cdr', '0013_fk_no_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlcdr',
            name='sip_pcap_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
