# Generated by Django 6.0.3 on 2026-06-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_cdr', '0014_sip_pcap_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlcdr',
            name='sip_pcap_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
