# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('access_control_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_control_name', models.CharField(max_length=255)),
                ('access_control_default', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', max_length=10)),
                ('access_control_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_access_controls',
            },
        ),
        migrations.CreateModel(
            name='AccessControlNode',
            fields=[
                ('access_control_node_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_control_node_type', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('access_control_node_cidr', models.CharField(max_length=255)),
                ('access_control_node_domain', models.CharField(blank=True, max_length=255)),
                ('access_control_node_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('access_control', models.ForeignKey(db_column='access_control_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='access_controls.accesscontrol')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_access_control_nodes',
            },
        ),
    ]
