# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_hours', '0002_remove_unique_day_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workinghoursday',
            name='unique_working_hours_day',
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='closed_dest_type',
            field=models.CharField(choices=[('extension', 'Extension'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('ivr_menu', 'IVR Menu'), ('conference', 'Conference'), ('external', 'External Number'), ('hangup', 'Hangup'), ('custom_destination', 'Custom Destination')], default='hangup', help_text='Where to route calls outside open hours.', max_length=64),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='open_dest_type',
            field=models.CharField(choices=[('extension', 'Extension'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('ivr_menu', 'IVR Menu'), ('conference', 'Conference'), ('external', 'External Number'), ('hangup', 'Hangup'), ('custom_destination', 'Custom Destination')], default='hangup', help_text='Where to route calls during open hours.', max_length=64),
        ),
    ]
