# Generated by Django 5.1.5 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_default_gateway_and_more'),
        ('working_hours', '0005_merge'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workinghoursday',
            index=models.Index(fields=['working_hours', 'day_of_week'], name='v_working_h_working_18692f_idx'),
        ),
        migrations.AddIndex(
            model_name='workinghoursholiday',
            index=models.Index(fields=['working_hours', 'holiday_date'], name='v_working_h_working_3029a5_idx'),
        ),
    ]
