# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('call_recording_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_recording_filename', models.CharField(max_length=512)),
                ('call_recording_caller_id_name', models.CharField(blank=True, max_length=255)),
                ('call_recording_caller_id_number', models.CharField(blank=True, max_length=255)),
                ('call_recording_destination_number', models.CharField(blank=True, max_length=255)),
                ('call_recording_start_stamp', models.DateTimeField(blank=True, null=True)),
                ('call_recording_duration', models.IntegerField(default=0)),
                ('call_recording_billsec', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_call_recordings',
                'ordering': ['-insert_date'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('recording_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_name', models.CharField(max_length=255)),
                ('recording_filename', models.CharField(max_length=255)),
                ('recording_description', models.TextField(blank=True)),
                ('recording_base64', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_recordings',
            },
        ),
    ]
