# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='recording_format',
            field=models.CharField(blank=True, default='auto', max_length=32),
        ),
        migrations.AddField(
            model_name='recording',
            name='recording_volume',
            field=models.FloatField(default=1.0),
        ),
    ]
