# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFlow',
            fields=[
                ('call_flow_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_flow_name', models.CharField(max_length=255)),
                ('call_flow_extension', models.CharField(blank=True, max_length=255)),
                ('call_flow_feature_code', models.CharField(blank=True, max_length=50)),
                ('call_flow_status', models.CharField(default='true', max_length=10)),
                ('call_flow_sound', models.CharField(blank=True, max_length=255)),
                ('call_flow_greeting', models.CharField(blank=True, max_length=255)),
                ('call_flow_context', models.CharField(blank=True, max_length=128)),
                ('call_flow_enabled', models.BooleanField(default=True)),
                ('call_flow_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_call_flows',
            },
        ),
        migrations.CreateModel(
            name='CallFlowOption',
            fields=[
                ('call_flow_option_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_flow_option_order', models.IntegerField(default=0)),
                ('call_flow_option_enabled', models.BooleanField(default=True)),
                ('call_flow_option_destination', models.CharField(blank=True, max_length=255)),
                ('call_flow_option_app', models.CharField(blank=True, max_length=128)),
                ('call_flow_option_param', models.CharField(blank=True, max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('call_flow', models.ForeignKey(db_column='call_flow_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='call_flows.callflow')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_call_flow_options',
                'ordering': ['call_flow_option_order'],
            },
        ),
    ]
