# Generated by Django 5.1.5 on 2026-03-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_default_gateway_and_more'),
        ('custom_destinations', '0003_merge_20260323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdestination',
            name='dest_type',
            field=models.CharField(choices=[('extension', 'Extension'), ('ivr_menu', 'IVR Menu'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('time_condition', 'Time Condition'), ('working_hours', 'Working Hours'), ('call_flow', 'Call Flow'), ('conference', 'Conference'), ('external', 'External Number'), ('call_forward', 'Call Forward'), ('fax', 'Fax'), ('hangup', 'Hangup')], max_length=32),
        ),
        migrations.AlterField(
            model_name='customdestination',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
