# Generated by Django 6.0.3 on 2026-05-21 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_auditlog_user'),
        ('custom_destinations', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallerExtensionAffinity',
            fields=[
                ('affinity_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_number', models.CharField(db_index=True, help_text='Normalized customer number (last 10 digits, US).', max_length=32)),
                ('extension_number', models.CharField(help_text='Extension that most recently dialed this customer.', max_length=32)),
                ('last_seen', models.DateTimeField(db_index=True, help_text='Timestamp of the most recent outbound call that set this mapping.')),
                ('source', models.CharField(default='outbound', help_text='outbound | manual_seed — where this mapping came from.', max_length=16)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caller_extension_affinity', to='core.domain')),
                ('tenant', models.ForeignKey(db_column='tenant_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='caller_extension_affinity', to='core.tenant')),
            ],
            options={
                'db_table': 'v_caller_extension_affinity',
                'indexes': [models.Index(fields=['tenant', 'caller_number'], name='v_caller_ex_tenant__722261_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'caller_number'), name='uniq_affinity_tenant_caller')],
            },
        ),
    ]
