# Generated by Django 6.0.3 on 2026-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_destinations', '0006_callerextensionaffinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdestination',
            name='kind',
            field=models.CharField(choices=[('simple', 'Simple Destination'), ('sticky_last_agent', 'Route to Last Agent')], default='simple', help_text='Behavior selector. "Simple" routes straight to dest_type. Other kinds layer extra logic (e.g. sticky_last_agent looks up the caller-extension affinity first).', max_length=32),
        ),
    ]
