<<<<<<< Updated upstream
# Generated by Django 6.0.3 on 2026-06-02 10:37
=======
# Generated by Django 6.0.3 on 2026-06-02 10:02
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_destinations', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdestination',
            name='dest_type',
            field=models.CharField(choices=[('extension', 'Extension'), ('ivr_menu', 'IVR Menu'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('time_condition', 'Time Condition'), ('working_hours', 'Working Hours'), ('call_flow', 'Call Flow'), ('conference', 'Conference'), ('external', 'External Number'), ('call_forward', 'Call Forward'), ('fax', 'Fax'), ('hangup', 'Hangup'), ('custom_destination', 'Custom Destination')], max_length=32),
        ),
    ]
