# Generated by Django 6.0.3 on 2026-06-08 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_destinations', '0015_alter_customdestination_dest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdestination',
            name='toggle_default_on',
            field=models.BooleanField(default=True, help_text='Initial / fallback state when no value is stored yet (True = ON / green).'),
        ),
        migrations.AddField(
            model_name='customdestination',
            name='toggle_feature_code',
            field=models.CharField(blank=True, default='', help_text='Dial string that flips the toggle, e.g. "*71". Required for toggle kind.', max_length=16),
        ),
        migrations.AddField(
            model_name='customdestination',
            name='toggle_off_dest',
            field=models.ForeignKey(blank=True, db_column='toggle_off_dest_uuid', help_text='Where calls go while the toggle is OFF (red). Another CustomDestination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_destinations.customdestination'),
        ),
        migrations.AddField(
            model_name='customdestination',
            name='toggle_on_dest',
            field=models.ForeignKey(blank=True, db_column='toggle_on_dest_uuid', help_text='Where calls go while the toggle is ON (green). Another CustomDestination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_destinations.customdestination'),
        ),
        migrations.AlterField(
            model_name='customdestination',
            name='kind',
            field=models.CharField(choices=[('simple', 'Simple Destination'), ('sticky_last_agent', 'Route to Last Agent'), ('toggle', 'Toggle (BLF switch)')], default='simple', help_text='Behavior selector. "Simple" routes straight to dest_type. Other kinds layer extra logic (e.g. sticky_last_agent looks up the caller-extension affinity first).', max_length=32),
        ),
    ]
