# Generated by Django 6.0.3 on 2026-06-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_destinations', '0016_customdestination_toggle_default_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdestination',
            name='toggle_extension',
            field=models.CharField(blank=True, default='', help_text='Dialable BLF number for this toggle, e.g. "801". Subscribe a phone BLF key to it; dialing it flips the toggle. Required for toggle kind.', max_length=16),
        ),
        migrations.AlterField(
            model_name='customdestination',
            name='toggle_feature_code',
            field=models.CharField(blank=True, default='', help_text='Optional second dial string that also flips the toggle, e.g. "*71".', max_length=16),
        ),
    ]
