# Generated by Django 6.0.3 on 2026-06-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_destinations', '0017_customdestination_toggle_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdestination',
            name='toggle_state',
            field=models.BooleanField(default=True, help_text='Live canonical state — the source of truth. True = ON / green, False = OFF / red. Kept in sync with FreeSWITCH mod_db + presence; republished to phones on reboot/resync so the lamp never drifts.'),
        ),
        migrations.AlterField(
            model_name='customdestination',
            name='toggle_default_on',
            field=models.BooleanField(default=True, help_text='Initial state seeded into a brand-new toggle (True = ON / green).'),
        ),
    ]
