# Generated by Django 6.0.3 on 2026-06-18 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_allowed_fax_uuids'),
        ('custom_destinations', '0019_toggle_route_triple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerextensionaffinity',
            name='source',
            field=models.CharField(default='outbound', help_text='outbound | manual_seed | manual_ui — where this mapping came from.', max_length=16),
        ),
        migrations.AlterField(
            model_name='customdestination',
            name='toggle_off_dest',
            field=models.ForeignKey(blank=True, db_column='toggle_off_dest_uuid', help_text='Legacy OFF-branch FK to another CustomDestination. Superseded by toggle_off_type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_destinations.customdestination'),
        ),
        migrations.AlterField(
            model_name='customdestination',
            name='toggle_on_dest',
            field=models.ForeignKey(blank=True, db_column='toggle_on_dest_uuid', help_text='Legacy ON-branch FK to another CustomDestination. Superseded by toggle_on_type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_destinations.customdestination'),
        ),
        migrations.CreateModel(
            name='ToggleEvent',
            fields=[
                ('toggle_event_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_state', models.BooleanField(help_text='True = ON, False = OFF after the flip.')),
                ('source', models.CharField(choices=[('blf', 'Phone BLF key'), ('ui', 'Web UI'), ('api', 'API'), ('dialplan', 'Dialplan'), ('resync', 'Resync')], default='ui', max_length=16)),
                ('actor', models.CharField(blank=True, default='', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('custom_destination', models.ForeignKey(db_column='custom_destination_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='toggle_events', to='custom_destinations.customdestination')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toggle_events', to='core.tenant')),
            ],
            options={
                'db_table': 'v_custom_destination_toggle_events',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['custom_destination', '-created'], name='v_custom_de_custom__078a99_idx')],
            },
        ),
    ]
