# Generated by Django 6.0.3 on 2026-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='peerstatehistory',
            new_name='esl_peer_st_extensi_77a70e_idx',
            old_name='esl_psh_ext_start_idx',
        ),
        migrations.RenameIndex(
            model_name='peerstatehistory',
            new_name='esl_peer_st_extensi_e57f7f_idx',
            old_name='esl_psh_ext_end_idx',
        ),
        migrations.AlterField(
            model_name='peerstatehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
