# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceCenter',
            fields=[
                ('conference_center_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference_center_name', models.CharField(max_length=128)),
                ('conference_center_extension', models.CharField(blank=True, default='', max_length=32)),
                ('conference_center_enabled', models.BooleanField(default=True)),
                ('conference_center_description', models.TextField(blank=True, default='')),
                ('domain', models.ForeignKey(db_column='domain_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='conference_centers', to='core.domain')),
            ],
            options={
                'db_table': 'v_conference_centers',
            },
        ),
        migrations.CreateModel(
            name='ConferenceProfile',
            fields=[
                ('conference_profile_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference_profile_name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_profiles', to='core.domain')),
            ],
            options={
                'db_table': 'v_conference_profiles',
            },
        ),
        migrations.CreateModel(
            name='ConferenceProfileSetting',
            fields=[
                ('conference_profile_setting_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference_profile_setting_name', models.CharField(max_length=128)),
                ('conference_profile_setting_value', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('conference_profile', models.ForeignKey(db_column='conference_profile_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='conferences.conferenceprofile')),
            ],
            options={
                'db_table': 'v_conference_profile_settings',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=128)),
                ('conference_extension', models.CharField(blank=True, default='', max_length=32)),
                ('conference_pin', models.CharField(blank=True, default='', max_length=16)),
                ('conference_flags', models.CharField(blank=True, default='', max_length=256)),
                ('conference_max_members', models.IntegerField(default=0)),
                ('conference_record', models.BooleanField(default=False)),
                ('conference_record_file', models.CharField(blank=True, default='', max_length=512)),
                ('conference_enabled', models.BooleanField(default=True)),
                ('conference_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='core.domain')),
                ('conference_profile', models.ForeignKey(blank=True, db_column='conference_profile_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.conferenceprofile')),
            ],
            options={
                'db_table': 'v_conferences',
                'unique_together': {('domain', 'conference_name')},
            },
        ),
    ]
