# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_label', models.CharField(blank=True, max_length=255)),
                ('device_mac_address', models.CharField(blank=True, max_length=255)),
                ('device_vendor', models.CharField(blank=True, max_length=255)),
                ('device_model', models.CharField(blank=True, max_length=255)),
                ('device_firmware_version', models.CharField(blank=True, max_length=255)),
                ('device_profile_uuid', models.UUIDField(blank=True, null=True)),
                ('device_enabled', models.BooleanField(default=True)),
                ('device_enabled_date', models.DateTimeField(blank=True, null=True)),
                ('device_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceLine',
            fields=[
                ('device_line_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.IntegerField(default=1)),
                ('device_line_server_address', models.CharField(blank=True, max_length=255)),
                ('device_line_label', models.CharField(blank=True, max_length=255)),
                ('device_line_username', models.CharField(blank=True, max_length=255)),
                ('device_line_password', models.CharField(blank=True, max_length=255)),
                ('device_line_auth_id', models.CharField(blank=True, max_length=255)),
                ('device_line_extension', models.CharField(blank=True, max_length=255)),
                ('device_line_display_name', models.CharField(blank=True, max_length=255)),
                ('device_line_enabled', models.BooleanField(default=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('device', models.ForeignKey(db_column='device_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='devices.device')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_device_lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSetting',
            fields=[
                ('device_setting_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_setting_name', models.CharField(max_length=255)),
                ('device_setting_value', models.TextField(blank=True)),
                ('device_setting_enabled', models.BooleanField(default=True)),
                ('device_setting_description', models.TextField(blank=True)),
                ('device', models.ForeignKey(db_column='device_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='devices.device')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_device_settings',
            },
        ),
    ]
