# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingGroup',
            fields=[
                ('ring_group_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ring_group_name', models.CharField(max_length=128)),
                ('ring_group_extension', models.CharField(blank=True, default='', max_length=32)),
                ('ring_group_greeting', models.CharField(blank=True, default='', max_length=256)),
                ('ring_group_cid_name_prefix', models.CharField(blank=True, default='', max_length=64)),
                ('ring_group_cid_number_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('ring_group_caller_id_name', models.CharField(blank=True, default='', max_length=128)),
                ('ring_group_caller_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('ring_group_strategy', models.CharField(choices=[('simultaneous', 'Simultaneous'), ('sequence', 'Sequence'), ('enterprise', 'Enterprise'), ('rollover', 'Rollover')], default='simultaneous', max_length=32)),
                ('ring_group_call_timeout', models.IntegerField(default=30)),
                ('ring_group_timeout_app', models.CharField(blank=True, default='', max_length=64)),
                ('ring_group_timeout_data', models.CharField(blank=True, default='', max_length=256)),
                ('ring_group_ringback', models.CharField(blank=True, default='', max_length=256)),
                ('ring_group_context', models.CharField(default='default', max_length=128)),
                ('ring_group_enabled', models.BooleanField(default=True)),
                ('ring_group_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='ring_groups', to='core.domain')),
            ],
            options={
                'db_table': 'v_ring_groups',
                'unique_together': {('domain', 'ring_group_extension')},
            },
        ),
        migrations.CreateModel(
            name='RingGroupDestination',
            fields=[
                ('ring_group_destination_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_number', models.CharField(max_length=64)),
                ('destination_delay', models.IntegerField(default=0)),
                ('destination_timeout', models.IntegerField(default=30)),
                ('destination_prompt', models.CharField(blank=True, default='', max_length=256)),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('ring_group', models.ForeignKey(db_column='ring_group_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='ring_groups.ringgroup')),
            ],
            options={
                'db_table': 'v_ring_group_destinations',
                'ordering': ['destination_delay', 'destination_number'],
            },
        ),
    ]
