# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ring_groups', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_allow_additional_destinations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_allow_fmfm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_allow_redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_confirm_message',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_confirm_to_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_dial_timeout',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_fast_dial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_moh_sound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_skip_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_skip_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_timeout_external_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_timeout_target_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_timeout_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_use_custom_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ringgroup',
            name='ring_group_use_standard_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ringgroup',
            name='ring_group_call_timeout',
            field=models.IntegerField(default=60),
        ),
    ]
