# Generated by Django 5.1.5 on 2026-02-19 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SofiaGlobalSetting',
            fields=[
                ('sofia_global_setting_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sofia_global_setting_name', models.CharField(max_length=128)),
                ('sofia_global_setting_value', models.TextField(blank=True, default='')),
                ('sofia_global_setting_enabled', models.BooleanField(default=True)),
                ('sofia_global_setting_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_sofia_global_settings',
                'ordering': ['sofia_global_setting_name'],
            },
        ),
    ]
