# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('email_queue_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_queue_from', models.EmailField(blank=True, max_length=254)),
                ('email_queue_to', models.EmailField(max_length=254)),
                ('email_queue_cc', models.EmailField(blank=True, max_length=254)),
                ('email_queue_subject', models.CharField(max_length=512)),
                ('email_queue_body', models.TextField()),
                ('email_queue_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('email_queue_retry_count', models.IntegerField(default=0)),
                ('email_queue_date', models.DateTimeField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_email_queue',
                'ordering': ['-insert_date'],
            },
        ),
    ]
