# Generated by Django 5.1.5 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_default_gateway_and_more'),
        ('email_queue', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['email_queue_status', 'insert_date'], name='v_email_que_email_q_662676_idx'),
        ),
    ]
