# Generated by Django 6.0.3 on 2026-08-17 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_allowed_actions'),
        ('email_queue', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fax_status', 'Fax status'), ('fax_inbound', 'Inbound fax'), ('voicemail', 'Voicemail'), ('account', 'Account'), ('queue', 'Queue drain'), ('other', 'Other')], default='other', max_length=32)),
                ('related_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('email_from', models.CharField(blank=True, default='', max_length=320)),
                ('email_to', models.TextField(blank=True, default='')),
                ('email_cc', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('attachment_names', models.TextField(blank=True, default='')),
                ('attachment_count', models.PositiveSmallIntegerField(default=0)),
                ('attachment_bytes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'v_email_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='v_email_del_status_714111_idx'), models.Index(fields=['category', 'created_at'], name='v_email_del_categor_2aaabb_idx'), models.Index(fields=['created_at'], name='v_email_del_created_c9a403_idx')],
            },
        ),
    ]
