# Generated by Django 6.0.3 on 2026-07-17 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuPeak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('system_cpu_peak', models.FloatField(help_text='Peak whole-server CPU %, 0-100')),
                ('freeswitch_cpu_peak', models.FloatField(help_text='Peak freeswitch process CPU % (may exceed 100 = sum over cores)')),
                ('freeswitch_cpu_peak_norm', models.FloatField(help_text='freeswitch_cpu_peak divided by core count, comparable to system %')),
                ('cpu_count', models.IntegerField(help_text='Logical CPU cores at sample time')),
                ('load_avg_1m', models.FloatField(blank=True, null=True)),
                ('freeswitch_running', models.BooleanField(default=True)),
                ('samples', models.IntegerField(default=0, help_text='Number of samples in this window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CPU peak',
                'verbose_name_plural': 'CPU peaks',
                'db_table': 'system_cpu_peak',
                'ordering': ('-window_start',),
            },
        ),
    ]
