# Generated by Django 6.0.3 on 2026-07-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresPerf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('active_connections_peak', models.IntegerField(help_text='Peak backends in state=active')),
                ('total_connections_peak', models.IntegerField(help_text='Peak total backends')),
                ('max_connections', models.IntegerField(help_text='Configured max_connections')),
                ('cache_hit_ratio', models.FloatField(help_text='blks_hit / (blks_hit + blks_read) %, 0-100')),
                ('commits_per_sec', models.FloatField(help_text='xact_commit /s')),
                ('rollbacks_per_sec', models.FloatField(help_text='xact_rollback /s')),
                ('tuples_returned_per_sec', models.FloatField(help_text='tup_returned /s')),
                ('tuples_fetched_per_sec', models.FloatField(help_text='tup_fetched /s')),
                ('deadlocks', models.IntegerField(default=0, help_text='Deadlocks during window')),
                ('longest_query_seconds', models.FloatField(blank=True, help_text='Longest running query seen (s)', null=True)),
                ('samples', models.IntegerField(default=0, help_text='Number of samples in this window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PostgreSQL performance sample',
                'verbose_name_plural': 'PostgreSQL performance samples',
                'db_table': 'postgres_perf',
                'ordering': ('-window_start',),
            },
        ),
        migrations.CreateModel(
            name='SystemMetricSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('mem_pressure_some_peak', models.FloatField(blank=True, help_text='Peak PSI memory "some" avg10 %, 0-100', null=True)),
                ('mem_pressure_full_peak', models.FloatField(blank=True, help_text='Peak PSI memory "full" avg10 %, 0-100', null=True)),
                ('mem_used_percent_peak', models.FloatField(help_text='Peak RAM used %, 0-100')),
                ('swap_used_percent_peak', models.FloatField(help_text='Peak swap used %, 0-100')),
                ('disk_read_latency_ms', models.FloatField(help_text='Avg read latency over window (ms/op)')),
                ('disk_write_latency_ms', models.FloatField(help_text='Avg write latency over window (ms/op)')),
                ('disk_busy_percent_peak', models.FloatField(help_text='Peak disk busy % (util) over the window')),
                ('net_recv_bytes_per_sec', models.FloatField(help_text='Avg inbound throughput B/s')),
                ('net_sent_bytes_per_sec', models.FloatField(help_text='Avg outbound throughput B/s')),
                ('samples', models.IntegerField(default=0, help_text='Number of samples in this window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'system metric sample',
                'verbose_name_plural': 'system metric samples',
                'db_table': 'system_metric_sample',
                'ordering': ('-window_start',),
            },
        ),
    ]
