# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('fax_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fax_name', models.CharField(max_length=255)),
                ('fax_extension', models.CharField(blank=True, max_length=255)),
                ('fax_email', models.CharField(blank=True, max_length=255)),
                ('fax_email_connection', models.CharField(blank=True, max_length=255)),
                ('fax_caller_id_name', models.CharField(blank=True, max_length=255)),
                ('fax_caller_id_number', models.CharField(blank=True, max_length=255)),
                ('fax_forward_number', models.CharField(blank=True, max_length=255)),
                ('fax_toll_allow', models.CharField(blank=True, max_length=255)),
                ('fax_accountcode', models.CharField(blank=True, max_length=255)),
                ('fax_enabled', models.BooleanField(default=True)),
                ('fax_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_fax',
            },
        ),
        migrations.CreateModel(
            name='FaxFile',
            fields=[
                ('fax_file_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fax_file_type', models.CharField(default='pdf', max_length=10)),
                ('fax_file_name', models.CharField(max_length=512)),
                ('fax_file_path', models.CharField(blank=True, max_length=512)),
                ('fax_file_status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fax_file_pages', models.IntegerField(default=0)),
                ('fax_file_duration', models.IntegerField(default=0)),
                ('fax_file_caller_id_number', models.CharField(blank=True, max_length=255)),
                ('fax_file_destination_number', models.CharField(blank=True, max_length=255)),
                ('fax_file_date', models.DateTimeField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('fax', models.ForeignKey(db_column='fax_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fax.fax')),
            ],
            options={
                'db_table': 'v_fax_files',
                'ordering': ['-insert_date'],
            },
        ),
    ]
