# Generated by Django 5.1.5 on 2026-03-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0003_faxfile_channel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faxfile',
            name='fax',
            field=models.ForeignKey(blank=True, db_column='fax_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fax.fax'),
        ),
    ]
