# Generated by Django 6.0.3 on 2026-06-25 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_allowed_fax_uuids'),
        ('fax', '0010_fax_ftp_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaxFtpDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(default=21)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('remote_path', models.CharField(blank=True, default='', max_length=512)),
                ('remote_name', models.CharField(blank=True, default='', max_length=512)),
                ('use_tls', models.BooleanField(default=False)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_response', models.TextField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('fax', models.ForeignKey(blank=True, db_column='fax_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ftp_deliveries', to='fax.fax')),
                ('fax_file', models.ForeignKey(blank=True, db_column='fax_file_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ftp_deliveries', to='fax.faxfile')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'v_fax_ftp_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fax', 'status'], name='v_fax_ftp_d_fax_uui_ccf604_idx'), models.Index(fields=['status', 'created_at'], name='v_fax_ftp_d_status_624454_idx')],
            },
        ),
    ]
