# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dialplan_uuid', models.UUIDField(blank=True, null=True)),
                ('destination_type', models.CharField(default='inbound', max_length=32)),
                ('destination_number', models.CharField(max_length=255)),
                ('destination_number_regex', models.CharField(blank=True, max_length=255)),
                ('destination_caller_id_name', models.CharField(blank=True, max_length=255)),
                ('destination_caller_id_number', models.CharField(blank=True, max_length=255)),
                ('destination_cid_name_prefix', models.CharField(blank=True, max_length=255)),
                ('destination_context', models.CharField(blank=True, max_length=128)),
                ('destination_app', models.CharField(blank=True, max_length=128)),
                ('destination_data', models.CharField(blank=True, max_length=512)),
                ('destination_bridge', models.TextField(blank=True)),
                ('destination_ringback', models.CharField(blank=True, max_length=255)),
                ('destination_hold_music', models.CharField(blank=True, max_length=255)),
                ('destination_record', models.BooleanField(default=False)),
                ('destination_accountcode', models.CharField(blank=True, max_length=255)),
                ('destination_enabled', models.BooleanField(default=True)),
                ('destination_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_destinations',
            },
        ),
    ]
