# Generated by Django 5.2.11 on 2026-02-23 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_tenant_code_autogen_and_domain_universal'),
        ('destinations', '0003_did_routing_redesign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['destination_number']},
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_external_number',
            field=models.CharField(blank=True, default='', help_text='Phone number to bridge to (only used when Destination type = External Number).', max_length=64, verbose_name='External number'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_target_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the Extension / IVR / Ring Group / etc. selected above.', null=True, verbose_name='Destination target'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_accountcode',
            field=models.CharField(blank=True, default='', help_text='Accountcode / billing code for CDR.', max_length=64),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_hold_music',
            field=models.CharField(blank=True, default='', help_text='Hold music URI. Leave blank to use system default.', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_number',
            field=models.CharField(help_text='DID / inbound phone number, e.g. +15551002000 or 5551002000.', max_length=64),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_number_regex',
            field=models.CharField(blank=True, default='', help_text='Optional regex override. Leave blank to match the number exactly.', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_record',
            field=models.BooleanField(default=False, help_text='Record all calls arriving on this DID.'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_ringback',
            field=models.CharField(blank=True, default='', help_text='Ringback tone URI, e.g. %(2000,4000,440,480) or us-ring.', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='domain',
            field=models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='core.domain'),
        ),
    ]
