# Generated by Django 5.2.11 on 2026-02-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destination_options_and_more'),
        ('destinations', '0004_fax_field'),
    ]

    operations = [
    ]
