# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_merge_20260323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='always_record',
            field=models.CharField(blank=True, choices=[('', 'No'), ('all', 'All'), ('local', 'Local'), ('outbound', 'Outbound'), ('inbound', 'Inbound')], default='', help_text='Record calls arriving on this DID.', max_length=16),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_type',
            field=models.CharField(blank=True, choices=[('extension', 'Extension'), ('ivr_menu', 'IVR Menu'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('time_condition', 'Time Condition'), ('working_hours', 'Working Hours'), ('call_flow', 'Call Flow'), ('conference', 'Conference'), ('external', 'External Number'), ('call_forward', 'Call Forward'), ('fax', 'Fax (direct fax receive)'), ('hangup', 'Hangup'), ('custom_destination', 'Custom Destination')], default='', max_length=32, verbose_name='Destination type (synced from first action)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_cid_number_prefix',
            field=models.CharField(blank=True, default='', help_text='Text prepended to inbound caller ID number.', max_length=64, verbose_name='Caller ID number prefix'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_record',
            field=models.BooleanField(default=False, help_text='Legacy record flag (superseded by always_record).'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='fax_email_destinations',
            field=models.CharField(blank=True, default='', help_text='Comma-separated email addresses to send received faxes to.', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='inbound_call_rate',
            field=models.CharField(blank=True, default='', help_text='Per-minute rate applied to inbound calls. Leave blank = not applied.', max_length=64),
        ),
        migrations.AlterField(
            model_name='destinationaction',
            name='dest_type',
            field=models.CharField(choices=[('extension', 'Extension'), ('ivr_menu', 'IVR Menu'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('time_condition', 'Time Condition'), ('working_hours', 'Working Hours'), ('call_flow', 'Call Flow'), ('conference', 'Conference'), ('external', 'External Number'), ('call_forward', 'Call Forward'), ('fax', 'Fax (direct fax receive)'), ('hangup', 'Hangup'), ('custom_destination', 'Custom Destination')], max_length=32),
        ),
    ]
