# Generated by Django 5.1.5 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_default_gateway_and_more'),
        ('destinations', '0012_merge'),
        ('fax', '0004_alter_faxfile_fax'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['destination_number'], name='v_destinati_destina_23a73e_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['tenant', 'destination_number'], name='v_destinati_tenant__3b71a4_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['destination_enabled'], name='v_destinati_destina_4cad0a_idx'),
        ),
    ]
