<<<<<<< Updated upstream
# Generated by Django 6.0.3 on 2026-06-02 10:37
=======
# Generated by Django 6.0.3 on 2026-04-28 01:59
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< Updated upstream
        ('core', '0014_alter_auditlog_user'),
=======
        ('core', '0012_add_is_occupied_parked_call_uuid'),
>>>>>>> Stashed changes
        ('destinations', '0013_add_performance_indexes'),
        ('fax', '0007_faxfile_caller_id_name_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_type',
            field=models.CharField(blank=True, choices=[('extension', 'Extension'), ('ivr_menu', 'IVR Menu'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('time_condition', 'Time Condition'), ('working_hours', 'Working Hours'), ('call_flow', 'Call Flow'), ('conference', 'Conference'), ('external', 'External Number'), ('call_forward', 'Call Forward'), ('fax', 'Fax (direct fax receive)'), ('hangup', 'Hangup'), ('custom_destination', 'Custom Destination'), ('call_park', 'Call Park')], default='', max_length=32, verbose_name='Destination type (synced from first action)'),
        ),
        migrations.AlterField(
            model_name='destinationaction',
            name='dest_type',
            field=models.CharField(choices=[('extension', 'Extension'), ('ivr_menu', 'IVR Menu'), ('ring_group', 'Ring Group'), ('voicemail', 'Voicemail'), ('time_condition', 'Time Condition'), ('working_hours', 'Working Hours'), ('call_flow', 'Call Flow'), ('conference', 'Conference'), ('external', 'External Number'), ('call_forward', 'Call Forward'), ('fax', 'Fax (direct fax receive)'), ('hangup', 'Hangup'), ('custom_destination', 'Custom Destination'), ('call_park', 'Call Park')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(fields=('destination_number',), name='unique_destination_number'),
        ),
    ]
