# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBroadcast',
            fields=[
                ('call_broadcast_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_broadcast_name', models.CharField(max_length=255)),
                ('call_broadcast_caller_id_name', models.CharField(blank=True, max_length=255)),
                ('call_broadcast_caller_id_number', models.CharField(blank=True, max_length=255)),
                ('call_broadcast_timeout', models.IntegerField(default=60)),
                ('call_broadcast_context', models.CharField(blank=True, max_length=128)),
                ('call_broadcast_recording', models.CharField(blank=True, max_length=512)),
                ('call_broadcast_enabled', models.BooleanField(default=True)),
                ('call_broadcast_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_call_broadcast',
            },
        ),
        migrations.CreateModel(
            name='CallBroadcastContact',
            fields=[
                ('call_broadcast_contact_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_broadcast_contact_number', models.CharField(max_length=255)),
                ('call_broadcast_contact_status', models.CharField(default='pending', max_length=20)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('call_broadcast', models.ForeignKey(db_column='call_broadcast_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='call_broadcast.callbroadcast')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_call_broadcast_contacts',
            },
        ),
    ]
