# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('extension_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=32)),
                ('number_alias', models.CharField(blank=True, default='', max_length=32)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('accountcode', models.CharField(blank=True, default='', max_length=32)),
                ('effective_caller_id_name', models.CharField(blank=True, default='', max_length=128)),
                ('effective_caller_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('outbound_caller_id_name', models.CharField(blank=True, default='', max_length=128)),
                ('outbound_caller_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('emergency_caller_id_name', models.CharField(blank=True, default='', max_length=128)),
                ('emergency_caller_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('directory_full_name', models.CharField(blank=True, default='', max_length=256)),
                ('directory_visible', models.BooleanField(default=True)),
                ('directory_exten_visible', models.BooleanField(default=True)),
                ('limit_max', models.IntegerField(default=5)),
                ('limit_destination', models.CharField(blank=True, default='', max_length=256)),
                ('call_timeout', models.IntegerField(default=30)),
                ('call_group', models.CharField(blank=True, default='', max_length=32)),
                ('call_screen_enabled', models.BooleanField(default=False)),
                ('user_record', models.CharField(blank=True, choices=[('', 'Disabled'), ('all', 'All'), ('local', 'Local'), ('outbound', 'Outbound'), ('inbound', 'Inbound')], default='', max_length=32)),
                ('voicemail_enabled', models.BooleanField(default=True)),
                ('voicemail_id', models.CharField(blank=True, default='', max_length=32)),
                ('voicemail_password', models.CharField(blank=True, default='', max_length=32)),
                ('voicemail_mail_to', models.EmailField(blank=True, default='', max_length=254)),
                ('voicemail_file', models.CharField(choices=[('attach', 'Attach'), ('link', 'Link'), ('none', 'None')], default='attach', max_length=32)),
                ('voicemail_local_after_email', models.BooleanField(default=True)),
                ('forward_all_enabled', models.BooleanField(default=False)),
                ('forward_all_destination', models.CharField(blank=True, default='', max_length=32)),
                ('forward_busy_enabled', models.BooleanField(default=False)),
                ('forward_busy_destination', models.CharField(blank=True, default='', max_length=32)),
                ('forward_no_answer_enabled', models.BooleanField(default=False)),
                ('forward_no_answer_destination', models.CharField(blank=True, default='', max_length=32)),
                ('forward_user_not_registered_enabled', models.BooleanField(default=False)),
                ('forward_user_not_registered_destination', models.CharField(blank=True, default='', max_length=32)),
                ('user_context', models.CharField(default='default', max_length=128)),
                ('toll_allow', models.CharField(blank=True, default='', max_length=256)),
                ('auth_acl', models.CharField(blank=True, default='', max_length=256)),
                ('cidr', models.CharField(blank=True, default='', max_length=256)),
                ('sip_force_contact', models.CharField(blank=True, default='', max_length=32)),
                ('sip_force_expires', models.IntegerField(blank=True, null=True)),
                ('max_registrations', models.IntegerField(default=1)),
                ('absolute_codec_string', models.CharField(blank=True, default='', max_length=256)),
                ('force_ping', models.BooleanField(default=False)),
                ('sip_bypass_media', models.CharField(blank=True, default='', max_length=32)),
                ('hold_music', models.CharField(blank=True, default='', max_length=256)),
                ('mwi_account', models.CharField(blank=True, default='', max_length=256)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='core.domain')),
            ],
            options={
                'db_table': 'v_extensions',
                'ordering': ['extension'],
                'unique_together': {('domain', 'extension')},
            },
        ),
        migrations.CreateModel(
            name='ExtensionUser',
            fields=[
                ('extension_user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('extension', models.ForeignKey(db_column='extension_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='extension_users', to='extensions.extension')),
                ('user', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='extension_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v_extension_users',
                'unique_together': {('extension', 'user')},
            },
        ),
    ]
