# Generated by Django 5.1.5 on 2026-02-19 11:23

from django.db import migrations, models


def backfill_sip_username(apps, schema_editor):
    Extension = apps.get_model('extensions', 'Extension')
    for ext in Extension.objects.select_related('tenant').all():
        tenant_code = ext.tenant.tenant_code if ext.tenant else ''
        ext.sip_username = f'{ext.extension}-{tenant_code}' if tenant_code else ext.extension
        ext.save(update_fields=['sip_username'])


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='sip_username',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Auto-generated SIP username: extension + tenant_code (e.g. 1001ACM).', max_length=64),
        ),
        migrations.RunPython(backfill_sip_username, reverse_code=migrations.RunPython.noop),
    ]
