# Generated by Django 5.1.5 on 2026-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_add_sip_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='extension',
            name='sip_username',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Auto-generated SIP username: extension-tenant_code (e.g. 1001-ACM).', max_length=64),
        ),
    ]
