# Generated by Django 5.1.5 on 2026-02-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0004_password_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='call_forward_active',
            field=models.BooleanField(default=False, help_text='Enable additional destinations. All forwarding rules below are active only when this is checked.'),
        ),
        migrations.AddField(
            model_name='extension',
            name='codec_preference',
            field=models.CharField(blank=True, default='', help_text='Comma-separated preferred codec list e.g. PCMU,PCMA,G729. Overrides profile default.', max_length=256),
        ),
        migrations.AddField(
            model_name='extension',
            name='forward_on_condition',
            field=models.CharField(blank=True, default='', help_text='Dialplan condition expression (e.g. ${caller_id_number} == 1234).', max_length=256),
        ),
        migrations.AddField(
            model_name='extension',
            name='forward_on_condition_destination',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='extension',
            name='forward_on_condition_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extension',
            name='forward_all_destination',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='extension',
            name='forward_busy_destination',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='extension',
            name='forward_no_answer_destination',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='extension',
            name='forward_user_not_registered_destination',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
