# Generated by Django 5.2.11 on 2026-02-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0006_add_outbound_route_and_xheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='codec_preference',
            field=models.CharField(blank=True, default='', help_text='Comma-separated codec list e.g. PCMU,PCMA,G722. PCMU,PCMA always safe. G729 needs license.', max_length=256),
        ),
        migrations.AlterField(
            model_name='extension',
            name='outbound_xheader_name',
            field=models.CharField(blank=True, default='', help_text='SIP X-header name sent on outbound calls, e.g. X-Tenant-ID. Must start with X-.', max_length=64, verbose_name='Custom X-header name'),
        ),
    ]
