# Generated by Django 5.2.11 on 2026-02-23 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_tenant_code_autogen_and_domain_universal'),
        ('extensions', '0007_alter_extension_codec_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='domain',
            field=models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to='core.domain'),
        ),
        migrations.AlterField(
            model_name='extensionuser',
            name='domain',
            field=models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain'),
        ),
    ]
