# Generated by Django 5.2.11 on 2026-02-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0008_auto_populate_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='sip_bypass_media',
            field=models.CharField(blank=True, choices=[('', 'Disabled — FreeSWITCH in RTP path (default)'), ('true', 'Bypass Media — direct RTP between endpoints'), ('proxy', 'Proxy Media — FS forwards RTP without processing')], default='', help_text='Bypass Media: FreeSWITCH exits the RTP path; endpoints talk directly. Proxy Media: FreeSWITCH stays in path but only forwards, no re-encoding.', max_length=32),
        ),
    ]
