# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0010_add_outbound_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='rtp_encryption',
            field=models.BooleanField(default=False, help_text='Require SRTP for RTP encryption.'),
        ),
        migrations.AddField(
            model_name='extension',
            name='transport',
            field=models.CharField(blank=True, choices=[('any', 'Any (UDP, TCP, TLS and WebRTC)'), ('udp', 'UDP only'), ('tcp', 'TCP only'), ('tls', 'TLS only'), ('wss', 'WebRTC (WSS) only')], default='any', help_text='Allowed SIP transport for this extension.', max_length=16),
        ),
        migrations.AddField(
            model_name='extension',
            name='webrtc_support',
            field=models.BooleanField(default=False, help_text='Enable WebRTC-specific params (SRTP, WSS transport) in directory XML.'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='limit_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extension',
            name='max_registrations',
            field=models.IntegerField(default=0),
        ),
    ]
