# Generated by Django 6.0.3 on 2026-03-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0012_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='sip_bypass_media_webrtc',
            field=models.CharField(blank=True, choices=[('', 'Normal — FreeSWITCH in RTP path (default, required for WebRTC)'), ('proxy', 'Proxy Media — FS forwards only')], default='', help_text='Media mode for WebRTC (WSS) calls. Bypass is not available for WebRTC as it is incompatible with DTLS-SRTP.', max_length=32),
        ),
        migrations.AlterField(
            model_name='extension',
            name='sip_bypass_media',
            field=models.CharField(blank=True, choices=[('', 'Disabled — FreeSWITCH in RTP path (default)'), ('true', 'Bypass Media — direct RTP between endpoints'), ('proxy', 'Proxy Media — FS forwards RTP without processing')], default='', help_text='Media mode for UDP/TCP/TLS calls. Bypass: FreeSWITCH exits the RTP path. Proxy: FS stays in path but only forwards, no re-encoding.', max_length=32),
        ),
    ]
