# Generated by Django 6.0.3 on 2026-04-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0013_extension_reject_to_voicemail'),
        ('extensions', '0013_extension_sip_bypass_media_webrtc_and_more'),
    ]

    operations = [
    ]
