# Generated by Django 6.0.3 on 2026-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0014_merge_20260403_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='mobile_push_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
