# Generated by Django 6.0.3 on 2026-06-12 08:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0015_add_mobile_push_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='voicemail_mail_to',
            field=models.CharField(blank=True, default='', help_text='One or more email addresses, separated by commas.', max_length=512, validators=[core.validators.MultiEmailValidator()]),
        ),
    ]
