# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGuard',
            fields=[
                ('event_guard_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_guard_name', models.CharField(max_length=255)),
                ('event_guard_type', models.CharField(blank=True, max_length=64)),
                ('event_guard_expression', models.CharField(blank=True, max_length=512)),
                ('event_guard_action', models.CharField(blank=True, max_length=64)),
                ('event_guard_count', models.IntegerField(default=1)),
                ('event_guard_period', models.IntegerField(default=60)),
                ('event_guard_enabled', models.BooleanField(default=True)),
                ('event_guard_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_event_guard',
            },
        ),
    ]
