# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvrMenu',
            fields=[
                ('ivr_menu_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ivr_menu_name', models.CharField(max_length=255)),
                ('ivr_menu_extension', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_language', models.CharField(default='en', max_length=10)),
                ('ivr_menu_greet_long', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_greet_short', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_invalid_sound', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_exit_sound', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_confirm_macro', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_confirm_key', models.CharField(blank=True, max_length=10)),
                ('ivr_menu_tts_engine', models.CharField(blank=True, max_length=64)),
                ('ivr_menu_tts_voice', models.CharField(blank=True, max_length=64)),
                ('ivr_menu_confirm_attempts', models.IntegerField(default=3)),
                ('ivr_menu_timeout', models.IntegerField(default=3000)),
                ('ivr_menu_inter_digit_timeout', models.IntegerField(default=2000)),
                ('ivr_menu_max_failures', models.IntegerField(default=3)),
                ('ivr_menu_max_timeouts', models.IntegerField(default=3)),
                ('ivr_menu_digit_len', models.IntegerField(default=4)),
                ('ivr_menu_direct_dial', models.CharField(blank=True, max_length=10)),
                ('ivr_menu_ringback', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_cid_prefix', models.CharField(blank=True, max_length=64)),
                ('ivr_menu_enabled', models.BooleanField(default=True)),
                ('ivr_menu_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_ivr_menus',
            },
        ),
        migrations.CreateModel(
            name='IvrMenuOption',
            fields=[
                ('ivr_menu_option_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ivr_menu_option_digits', models.CharField(max_length=64)),
                ('ivr_menu_option_action', models.CharField(blank=True, max_length=64)),
                ('ivr_menu_option_param', models.CharField(blank=True, max_length=255)),
                ('ivr_menu_option_order', models.IntegerField(default=900)),
                ('ivr_menu_option_description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('ivr_menu', models.ForeignKey(db_column='ivr_menu_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ivr_menus.ivrmenu')),
            ],
            options={
                'db_table': 'v_ivr_menu_options',
                'ordering': ['ivr_menu_option_order'],
            },
        ),
    ]
