# Generated by Django 5.1.5 on 2026-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr_menus', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivrmenu',
            name='ivr_menu_allow_custom_codes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ivrmenu',
            name='ivr_menu_allow_feature_codes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ivrmenu',
            name='ivr_menu_allow_internal_dial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ivrmenu',
            name='ivr_menu_loop_invalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ivrmenu',
            name='ivr_menu_loop_timeout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ivrmenu',
            name='ivr_menu_playback_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ivrmenuoption',
            name='ivr_menu_option_dest_external_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ivrmenuoption',
            name='ivr_menu_option_dest_target_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ivrmenuoption',
            name='ivr_menu_option_dest_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
