# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voicemail',
            fields=[
                ('voicemail_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voicemail_id', models.CharField(max_length=32)),
                ('voicemail_password', models.CharField(blank=True, default='', max_length=32)),
                ('voicemail_mail_to', models.EmailField(blank=True, default='', max_length=254)),
                ('voicemail_sms_to', models.CharField(blank=True, default='', max_length=32)),
                ('voicemail_transcription_enabled', models.BooleanField(default=False)),
                ('voicemail_file', models.CharField(choices=[('attach', 'Attach'), ('link', 'Link'), ('none', 'None')], default='attach', max_length=32)),
                ('voicemail_local_after_email', models.BooleanField(default=True)),
                ('voicemail_enabled', models.BooleanField(default=True)),
                ('voicemail_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='voicemails', to='core.domain')),
            ],
            options={
                'db_table': 'v_voicemails',
                'unique_together': {('domain', 'voicemail_id')},
            },
        ),
        migrations.CreateModel(
            name='VoicemailDestination',
            fields=[
                ('voicemail_destination_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voicemail_destination_uuid2', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('voicemail', models.ForeignKey(db_column='voicemail_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='voicemails.voicemail')),
            ],
            options={
                'db_table': 'v_voicemail_destinations',
            },
        ),
        migrations.CreateModel(
            name='VoicemailMessage',
            fields=[
                ('voicemail_message_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_epoch', models.BigIntegerField(default=0)),
                ('read_epoch', models.BigIntegerField(default=0)),
                ('caller_id_name', models.CharField(blank=True, default='', max_length=128)),
                ('caller_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('message_num', models.IntegerField(default=0)),
                ('message_filename', models.CharField(blank=True, default='', max_length=512)),
                ('message_length', models.IntegerField(default=0)),
                ('message_status', models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('deleted', 'Deleted')], default='new', max_length=32)),
                ('message_priority', models.CharField(default='normal', max_length=16)),
                ('domain', models.ForeignKey(db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('voicemail', models.ForeignKey(db_column='voicemail_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='voicemails.voicemail')),
            ],
            options={
                'db_table': 'v_voicemail_messages',
                'ordering': ['-created_epoch'],
            },
        ),
        migrations.CreateModel(
            name='VoicemailOption',
            fields=[
                ('voicemail_option_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voicemail_option_digits', models.CharField(blank=True, default='', max_length=8)),
                ('voicemail_option_action', models.CharField(blank=True, default='', max_length=256)),
                ('voicemail_option_param', models.CharField(blank=True, default='', max_length=256)),
                ('voicemail_option_order', models.IntegerField(default=10)),
                ('domain', models.ForeignKey(db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('voicemail', models.ForeignKey(db_column='voicemail_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voicemails.voicemail')),
            ],
            options={
                'db_table': 'v_voicemail_options',
                'ordering': ['voicemail_option_order'],
            },
        ),
    ]
