# Generated by Django 5.2.11 on 2026-02-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_tenant_code_autogen_and_domain_universal'),
        ('voicemails', '0002_add_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voicemail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='post_voicemail_url',
            field=models.CharField(blank=True, default='', help_text='Called after a new voicemail is received. Use %%TENANTID%% as placeholder.', max_length=512, verbose_name='Post voicemail webhook URL'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use tenant default.', max_length=64),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_allow_callback',
            field=models.BooleanField(default=False, verbose_name='Allow callback'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_allow_dialout',
            field=models.BooleanField(default=False, verbose_name='Allow dial-out'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_allow_operator',
            field=models.BooleanField(default=False, verbose_name='Allow operator/extras during greeting'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_allow_review',
            field=models.BooleanField(default=False, verbose_name='Allow review before sending'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_auto_delete',
            field=models.BooleanField(default=False, verbose_name='Automatic delete'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_backup',
            field=models.BooleanField(default=False, verbose_name='Backup messages'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_delete_older_messages',
            field=models.BooleanField(default=False, verbose_name='Delete older messages'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_dial_by_name',
            field=models.BooleanField(default=False, verbose_name='Include in Dial-by-Name directory'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_envelope',
            field=models.BooleanField(default=True, help_text='Play date/time before each message.', verbose_name='Envelope playback'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_greeting',
            field=models.CharField(blank=True, choices=[('auto_no_instructions', 'Automatic with No Instructions'), ('auto_with_instructions', 'Automatic with Instructions'), ('recorded', 'Use Recorded Greeting')], default='auto_no_instructions', max_length=32, verbose_name='Greeting style'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_ivr_destination',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Voicemail IVR destination'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_language',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use tenant default.', max_length=16, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_max_len',
            field=models.IntegerField(default=3600, verbose_name='Max message length (seconds)'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_max_messages',
            field=models.IntegerField(default=100, verbose_name='Max number of messages'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_min_len',
            field=models.IntegerField(default=0, verbose_name='Min message length (seconds)'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_on_new_message',
            field=models.CharField(choices=[('nothing', 'Nothing special'), ('email', 'Send email'), ('both', 'Send email and keep message')], default='nothing', max_length=32, verbose_name='On new message'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_operator_destination',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Operator destination'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_pager',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Pager email'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_play_after',
            field=models.BooleanField(default=False, verbose_name='Play a message after the other'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_say_caller_id',
            field=models.BooleanField(default=False, verbose_name='Say caller ID'),
        ),
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_store_transcript',
            field=models.BooleanField(default=True, verbose_name='Store transcript'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='domain',
            field=models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voicemails', to='core.domain'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_file',
            field=models.CharField(choices=[('attach', 'Attach'), ('link', 'Link'), ('none', 'None')], default='attach', max_length=32, verbose_name='Attach message to email'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_local_after_email',
            field=models.BooleanField(default=True, verbose_name='Store message locally after email'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_mail_to',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_password',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_sms_to',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='SMS notification number'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_transcription_enabled',
            field=models.BooleanField(default=False, verbose_name='Generate transcript'),
        ),
        migrations.AlterUniqueTogether(
            name='voicemail',
            unique_together={('domain', 'voicemail_id')},
        ),
    ]
