# Generated by Django 5.2.11 on 2026-02-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemails', '0003_voicemail_full_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='caller_id_name',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='caller_id_number',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='message_filename',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='message_length',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='message_num',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='message_priority',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='message_status',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='voicemail',
        ),
        migrations.RemoveField(
            model_name='voicemailmessage',
            name='voicemail_message_uuid',
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='cid_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='cid_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='flags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='forwarded_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='in_folder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='message_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='read_flags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemailmessage',
            name='uuid',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicemailmessage',
            name='created_epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voicemailmessage',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voicemailmessage',
            name='read_epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='voicemailmessage',
            table='voicemail_msgs',
        ),
        migrations.CreateModel(
            name='VoicemailPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('name_path', models.CharField(blank=True, default='', max_length=255)),
                ('greeting_path', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'voicemail_prefs',
                'unique_together': {('username', 'domain')},
            },
        ),
    ]
