# Generated by Django 6.0.3 on 2026-04-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemails', '0008_voicemailtranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemailreadstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_transcription_enabled',
            field=models.BooleanField(default=True, verbose_name='Generate transcript'),
        ),
    ]
