# Generated by Django 6.0.3 on 2026-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_auditlog_user'),
        ('voicemails', '0008_voicemailtranscript'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voicemail',
            unique_together={('tenant', 'voicemail_id')},
        ),
        migrations.AddField(
            model_name='voicemailreadstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_transcription_enabled',
            field=models.BooleanField(default=True, verbose_name='Generate transcript'),
        ),
        migrations.AlterField(
            model_name='voicemailmessage',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
