# Generated by Django 6.0.3 on 2026-04-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_is_occupied_parked_call_uuid'),
        ('voicemails', '0009_voicemailreadstate_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voicemail',
            unique_together={('tenant', 'voicemail_id')},
        ),
    ]
