# Generated by Django 6.0.3 on 2026-05-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemails', '0010_alter_voicemail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemailmessage',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
