# Generated by Django 6.0.3 on 2026-06-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicemails', '0009_alter_voicemail_unique_together_and_more'),
        ('voicemails', '0011_alter_voicemailmessage_file_path'),
    ]

    operations = [
    ]
