# Generated by Django 6.0.3 on 2026-06-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_recording_recording_format_and_more'),
        ('voicemails', '0012_merge_20260602_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemail',
            name='voicemail_greeting_recording',
            field=models.ForeignKey(blank=True, db_column='greeting_recording_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recordings.recording', verbose_name='Greeting media file'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_greeting',
            field=models.CharField(blank=True, choices=[('auto_with_instructions', 'Automatic with Instructions'), ('tts_name', 'Text-to-Speech Greeting'), ('recorded_name', 'Recorded Name Greeting'), ('media_file', 'Media File Greeting')], default='auto_with_instructions', max_length=32, verbose_name='Greeting style'),
        ),
    ]
