# Generated by Django 6.0.3 on 2026-06-12 08:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemails', '0013_voicemail_voicemail_greeting_recording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemail',
            name='voicemail_mail_to',
            field=models.CharField(blank=True, default='', help_text='One or more email addresses, separated by commas.', max_length=512, validators=[core.validators.MultiEmailValidator()], verbose_name='Email'),
        ),
    ]
