# Generated by Django 5.1.5 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialplan',
            fields=[
                ('dialplan_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_uuid', models.UUIDField(blank=True, null=True)),
                ('dialplan_context', models.CharField(default='default', max_length=128)),
                ('dialplan_name', models.CharField(blank=True, default='', max_length=128)),
                ('dialplan_number', models.CharField(blank=True, default='', max_length=32)),
                ('dialplan_destination', models.BooleanField(default=False)),
                ('dialplan_continue', models.CharField(blank=True, default='', max_length=8)),
                ('dialplan_xml', models.TextField(blank=True, default='')),
                ('dialplan_order', models.IntegerField(default=100)),
                ('dialplan_enabled', models.BooleanField(default=True)),
                ('dialplan_global', models.BooleanField(default=False)),
                ('dialplan_description', models.TextField(blank=True, default='')),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insert_user', models.UUIDField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.UUIDField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialplans', to='core.domain')),
            ],
            options={
                'db_table': 'v_dialplans',
                'ordering': ['dialplan_order', 'dialplan_name'],
            },
        ),
        migrations.CreateModel(
            name='DialplanDetail',
            fields=[
                ('dialplan_detail_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dialplan_detail_tag', models.CharField(choices=[('condition', 'Condition'), ('action', 'Action'), ('anti-action', 'Anti-Action')], default='condition', max_length=32)),
                ('dialplan_detail_type', models.CharField(blank=True, default='', max_length=128)),
                ('dialplan_detail_data', models.CharField(blank=True, default='', max_length=4096)),
                ('dialplan_detail_break', models.CharField(blank=True, default='', max_length=32)),
                ('dialplan_detail_inline', models.BooleanField(default=False)),
                ('dialplan_detail_group', models.IntegerField(default=0)),
                ('dialplan_detail_order', models.IntegerField(default=10)),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dialplan', models.ForeignKey(db_column='dialplan_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dialplans.dialplan')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'db_table': 'v_dialplan_details',
                'ordering': ['dialplan_detail_group', 'dialplan_detail_order'],
            },
        ),
    ]
