# Generated by Django 5.1.5 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_default_gateway_and_more'),
        ('dialplans', '0002_add_tenant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dialplan',
            index=models.Index(fields=['dialplan_context', 'dialplan_enabled', 'dialplan_order'], name='v_dialplans_dialpla_e27f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='dialplan',
            index=models.Index(fields=['tenant', 'dialplan_context'], name='v_dialplans_tenant__ef7c53_idx'),
        ),
        migrations.AddIndex(
            model_name='dialplandetail',
            index=models.Index(fields=['dialplan', 'dialplan_detail_group', 'dialplan_detail_order'], name='v_dialplan__dialpla_e0e5e0_idx'),
        ),
    ]
