# Generated by Django 5.1.5 on 2026-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_fk_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_universal',
            field=models.BooleanField(default=False, help_text='If enabled, this domain is shared by all tenants.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_code',
            field=models.CharField(blank=True, help_text='Auto-generated from tenant name if left blank.', max_length=32, unique=True),
        ),
    ]
