# Generated by Django 5.1.5 on 2026-03-27 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_full_name_must_change_password'),
        ('gateways', '0004_alter_gateway_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_gateway',
            field=models.ForeignKey(blank=True, db_column='default_gateway_uuid', help_text='Default gateway used for outbound calls.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_tenants', to='gateways.gateway'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_gateway_priority',
            field=models.IntegerField(default=10, help_text='Lower number = higher priority (1 is highest).'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='fax_gateway',
            field=models.ForeignKey(blank=True, db_column='fax_gateway_uuid', help_text='Default gateway used for outbound fax transmission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fax_tenants', to='gateways.gateway'),
        ),
        migrations.AlterField(
            model_name='usertenantaccess',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='admin_accesses', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='usertenantaccess',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
