# Generated by Django 6.0.3 on 2026-05-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_is_occupied_parked_call_uuid'),
        ('core', '0013_tenant_provisioning_webhook_url_multi'),
    ]

    operations = [
    ]
