# Generated by Django 6.0.3 on 2026-05-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_auditlog_user'),
        ('core', '0014_merge_20260521_0637'),
    ]

    operations = [
    ]
