# Generated by Django 6.0.3 on 2026-06-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260521_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
