# Generated by Django 6.0.3 on 2026-06-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_allowed_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_fax_uuids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
