# Generated by Django 6.0.3 on 2026-07-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_allowed_fax_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_actions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
